# ai-generated: 100% - generated by Gemini API
from fastapi import FastAPI, HTTPException, Header, Request, Body
from fastapi.responses import JSONResponse
from fastapi.exceptions import RequestValidationError
from pydantic import BaseModel, Field, constr
from typing import Optional, Dict, Annotated
from datetime import datetime, timedelta, timezone
import uuid
import zoneinfo
import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from metrics import compute_metrics

app = FastAPI(title="svcdesk API")

@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    return JSONResponse(status_code=422, content={"error": "Validation Error"})

@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    if isinstance(exc.detail, dict) and "error" in exc.detail:
        return JSONResponse(status_code=exc.status_code, content=exc.detail)
    return JSONResponse(status_code=exc.status_code, content={"error": str(exc.detail)})

class SLA(BaseModel):
    ack_due_at: str
    resolve_due_at: str
    ack_due: str
    resolve_due: str
    ack_breached: bool = False
    resolve_breached: bool = False
    paused: bool = False

class TicketIn(BaseModel):
    title: constr(min_length=1, max_length=200)
    description: Optional[str] = ""
    reporter: dict
    impact: int = Field(..., ge=1, le=4)
    urgency: int = Field(..., ge=1, le=4)
    
    class Config:
        extra = 'ignore'

class TicketOut(BaseModel):
    id: str
    title: str
    description: str
    reporter: dict
    impact: int
    urgency: int
    priority: str
    state: str
    sla: SLA
    created_at: str
    acknowledged_at: Optional[str] = None
    resolved_at: Optional[str] = None
    closed_at: Optional[str] = None

db_tickets: Dict[str, TicketOut] = {}

def parse_clock(x_test_clock: str) -> datetime:
    if not x_test_clock:
        raise HTTPException(status_code=400, detail={"error": "Missing X-Test-Clock"})
    try:
        if x_test_clock.endswith("Z"):
            x_test_clock = x_test_clock[:-1] + "+00:00"
        dt = datetime.fromisoformat(x_test_clock)
        return dt.astimezone(timezone.utc).replace(tzinfo=None)
    except Exception:
        raise HTTPException(status_code=400, detail={"error": "Invalid X-Test-Clock format"})

def to_iso(dt: datetime) -> str:
    return dt.isoformat(timespec='seconds') + "Z"

def add_business_hours(start: datetime, hours: float) -> datetime:
    tz = zoneinfo.ZoneInfo("Europe/Warsaw")
    current = start.replace(tzinfo=timezone.utc).astimezone(tz)
    
    remaining_hours = hours
    while remaining_hours > 0:
        if current.weekday() >= 5:
            current = current.replace(hour=8, minute=0, second=0, microsecond=0) + timedelta(days=(7 - current.weekday()))
            continue
        
        if current.hour >= 16:
            current = current.replace(hour=8, minute=0, second=0, microsecond=0) + timedelta(days=1)
            continue
            
        if current.hour < 8:
            current = current.replace(hour=8, minute=0, second=0, microsecond=0)
            continue
            
        end_of_day = current.replace(hour=16, minute=0, second=0, microsecond=0)
        hours_to_end = (end_of_day - current).total_seconds() / 3600.0
        
        if remaining_hours <= hours_to_end:
            current = current + timedelta(hours=remaining_hours)
            remaining_hours = 0
        else:
            current = end_of_day
            remaining_hours -= hours_to_end

    return current.astimezone(timezone.utc).replace(tzinfo=None)

def is_paused_now(clock: datetime, is_wallclock: bool) -> bool:
    if is_wallclock:
        return False
    tz = zoneinfo.ZoneInfo("Europe/Warsaw")
    current = clock.replace(tzinfo=timezone.utc).astimezone(tz)
    if current.weekday() >= 5:
        return True
    if current.hour < 8 or current.hour >= 16:
        return True
    return False

@app.get("/health")
def health_check():
    return {"status": "ok"}

@app.post("/tickets", status_code=201, response_model=TicketOut)
def create_ticket(ticket: TicketIn, x_test_clock: Annotated[Optional[str], Header()] = None):
    clock = parse_clock(x_test_clock)
    
    matrix = {
        (1, 1): "P1", (1, 2): "P2", (1, 3): "P3", (1, 4): "P4",
        (2, 1): "P2", (2, 2): "P3", (2, 3): "P4", (2, 4): "P4",
        (3, 1): "P3", (3, 2): "P4", (3, 3): "P4", (3, 4): "P4",
        (4, 1): "P4", (4, 2): "P4", (4, 3): "P4", (4, 4): "P4",
    }
    base_priority = matrix.get((ticket.impact, ticket.urgency), "P4")
    
    priority = base_priority
    if ticket.reporter.get("vip") == True:
        if base_priority == "P4": priority = "P2"
        elif base_priority == "P3": priority = "P1"
        elif base_priority == "P2": priority = "P1"
        else: priority = "P1"

    sla_limits = {"P1": {"ack": 0.25, "res": 4}, "P2": {"ack": 1, "res": 8}, "P3": {"ack": 4, "res": 24}, "P4": {"ack": 8, "res": 72}}
    limits = sla_limits[priority]
    
    is_wallclock = (priority == "P1")
    
    if is_wallclock:
        ack_due = clock + timedelta(hours=limits["ack"])
        res_due = clock + timedelta(hours=limits["res"])
    else:
        ack_due = add_business_hours(clock, limits["ack"])
        res_due = add_business_hours(clock, limits["res"])
    
    new_id = str(uuid.uuid4())
    iso_ack = to_iso(ack_due)
    iso_res = to_iso(res_due)
    paused_status = is_paused_now(clock, is_wallclock)
    
    t = TicketOut(
        id=new_id,
        title=ticket.title,
        description=ticket.description,
        reporter=ticket.reporter,
        impact=ticket.impact,
        urgency=ticket.urgency,
        priority=priority,
        state="new",
        sla=SLA(ack_due_at=iso_ack, resolve_due_at=iso_res, ack_due=iso_ack, resolve_due=iso_res, paused=paused_status),
        created_at=to_iso(clock)
    )
    db_tickets[new_id] = t
    return t

def compute_sla(t: TicketOut, clock: datetime):
    is_wallclock = (t.priority == "P1")
    t.sla.paused = is_paused_now(clock, is_wallclock)
    
    if not t.acknowledged_at:
        t.sla.ack_breached = clock > parse_clock(t.sla.ack_due_at)
    else:
        t.sla.ack_breached = parse_clock(t.acknowledged_at) > parse_clock(t.sla.ack_due_at)
        
    if not t.resolved_at:
        t.sla.resolve_breached = clock > parse_clock(t.sla.resolve_due_at)
    else:
        t.sla.resolve_breached = parse_clock(t.resolved_at) > parse_clock(t.sla.resolve_due_at)

@app.get("/tickets/{ticket_id}")
def get_ticket(ticket_id: str, x_test_clock: Annotated[Optional[str], Header()] = None):
    clock = parse_clock(x_test_clock) if x_test_clock else datetime.utcnow()
    t = db_tickets.get(ticket_id)
    if not t:
        raise HTTPException(status_code=404, detail={"error": "Ticket not found"})
    
    compute_sla(t, clock)
    return t

@app.get("/tickets/{ticket_id}/sla")
def get_ticket_sla(ticket_id: str, x_test_clock: Annotated[Optional[str], Header()] = None):
    clock = parse_clock(x_test_clock) if x_test_clock else datetime.utcnow()
    t = db_tickets.get(ticket_id)
    if not t:
        raise HTTPException(status_code=404, detail={"error": "Ticket not found"})
        
    compute_sla(t, clock)
    return t.sla

@app.get("/tickets")
def list_tickets(state: Optional[str] = None, priority: Optional[str] = None, x_test_clock: Annotated[Optional[str], Header()] = None):
    clock = parse_clock(x_test_clock) if x_test_clock else datetime.utcnow()
    res = []
    for t in db_tickets.values():
        if state and t.state != state: continue
        if priority and t.priority != priority: continue
        compute_sla(t, clock)
        res.append(t)
    return res

@app.post("/tickets/{ticket_id}/{action}")
def ticket_action(ticket_id: str, action: str, x_test_clock: Annotated[Optional[str], Header()] = None):
    clock = parse_clock(x_test_clock)
    t = db_tickets.get(ticket_id)
    if not t:
        raise HTTPException(status_code=404, detail={"error": "Ticket not found"})
        
    if action == "ack":
        if t.state != "new": raise HTTPException(status_code=409, detail={"error": "Conflict"})
        t.state = "acknowledged"
        t.acknowledged_at = to_iso(clock)
        if clock > parse_clock(t.sla.ack_due_at):
            t.sla.ack_breached = True
            
    elif action == "start":
        if t.state != "acknowledged": raise HTTPException(status_code=409, detail={"error": "Conflict"})
        t.state = "in_progress"
        
    elif action == "resolve":
        if t.state != "in_progress": raise HTTPException(status_code=409, detail={"error": "Conflict"})
        t.state = "resolved"
        t.resolved_at = to_iso(clock)
        if clock > parse_clock(t.sla.resolve_due_at):
            t.sla.resolve_breached = True
            
    elif action == "close":
        if t.state != "resolved": raise HTTPException(status_code=409, detail={"error": "Conflict"})
        t.state = "closed"
        t.closed_at = to_iso(clock)
        
    elif action == "reopen":
        if t.state == "closed":
            raise HTTPException(status_code=409, detail={"error": "C2: Closed tickets are immutable"})
        if t.state != "resolved":
            raise HTTPException(status_code=409, detail={"error": "Conflict"})
        if clock > parse_clock(t.resolved_at) + timedelta(days=7):
            raise HTTPException(status_code=409, detail={"error": "Cannot reopen after 7 days"})
        t.state = "in_progress"
    else:
        raise HTTPException(status_code=404, detail={"error": "Action not found"})
        
    return t

@app.get("/dora/ticket-events")
def get_ticket_events():
    events = []
    for t_id, t in db_tickets.items():
        if t.created_at:
            events.append({"ticket_id": t_id, "at": t.created_at, "phase": "created", "priority": t.priority, "state": "new"})
        if t.acknowledged_at:
            events.append({"ticket_id": t_id, "at": t.acknowledged_at, "phase": "acknowledged", "priority": t.priority, "state": "acknowledged"})
        if t.resolved_at:
            events.append({"ticket_id": t_id, "at": t.resolved_at, "phase": "resolved", "priority": t.priority, "state": "resolved"})
        if t.closed_at:
            events.append({"ticket_id": t_id, "at": t.closed_at, "phase": "closed", "priority": t.priority, "state": "closed"})
    
    events.sort(key=lambda x: (x["at"], x["ticket_id"]))
    return events

@app.post("/dora/metrics")
def post_dora_metrics(payload: dict = Body(...)):
    try:
        result = compute_metrics(payload)
        return result
    except ValueError as e:
        return JSONResponse(status_code=400, content={"error": str(e)})