# ai-generated: 100% - Generated by Antigravity
import json
from datetime import datetime, timezone
import statistics
import decimal

def parse_iso(dt_str: str) -> datetime:
    if not dt_str:
        raise ValueError("Empty datetime")
    if dt_str.endswith("Z"):
        dt_str = dt_str[:-1] + "+00:00"
    return datetime.fromisoformat(dt_str).astimezone(timezone.utc)

def round_half_up(n, decimals=0):
    d = decimal.Decimal(str(n))
    if decimals == 0:
        return int(d.quantize(decimal.Decimal('1'), rounding=decimal.ROUND_HALF_UP))
    else:
        return float(d.quantize(decimal.Decimal('1.' + '0'*decimals), rounding=decimal.ROUND_HALF_UP))

def median(lst):
    if not lst:
        return None
    lst = sorted(lst)
    n = len(lst)
    if n % 2 == 1:
        return round_half_up(lst[n//2], 0)
    else:
        return round_half_up((lst[n//2 - 1] + lst[n//2]) / 2.0, 0)

def compute_metrics(payload: dict) -> dict:
    if not isinstance(payload, dict):
        raise ValueError("Payload must be an object")
    if "window" not in payload or not isinstance(payload["window"], dict):
        raise ValueError("Missing window")
    window = payload["window"]
    if "from" not in window or "to" not in window:
        raise ValueError("Missing window.from or window.to")
    
    try:
        window_from = parse_iso(window["from"])
        window_to = parse_iso(window["to"])
    except Exception:
        raise ValueError("Invalid RFC3339 in window")
        
    if window_to <= window_from:
        raise ValueError("window.to must be after window.from")
        
    if "events" not in payload or not isinstance(payload["events"], list):
        raise ValueError("Missing or invalid events array")
        
    events = payload["events"]
    
    # Dedup events (first wins)
    unique_events = {}
    for ev in events:
        if not isinstance(ev, dict) or "event_id" not in ev or "type" not in ev or "at" not in ev:
            raise ValueError("Malformed event")
        ev_id = ev["event_id"]
        if ev_id not in unique_events:
            unique_events[ev_id] = ev
            
    events_list = list(unique_events.values())
    
    commits = {}
    deployments = {}
    incidents = {}
    
    for ev in events_list:
        try:
            ev_at = parse_iso(ev["at"])
        except:
            raise ValueError("Invalid event timestamp")
            
        t = ev["type"]
        if t == "commit":
            if "sha" not in ev or "branch" not in ev or "change_id" not in ev or "reverts" not in ev:
                raise ValueError("Malformed commit")
            if ev["reverts"] is None and ev.get("change_id") is None:
                 raise ValueError("Malformed commit change_id")
            if ev["reverts"] is not None and ev.get("change_id") is not None:
                 raise ValueError("Malformed commit change_id")
            commits[ev["sha"]] = {"at": ev_at, "sha": ev["sha"], "branch": ev["branch"], "change_id": ev["change_id"], "reverts": ev["reverts"]}
        elif t == "deployment":
            if "deployment_id" not in ev or "environment" not in ev or "outcome" not in ev or "commits" not in ev or "unplanned" not in ev or "caused_by" not in ev:
                raise ValueError("Malformed deployment")
            deployments[ev["deployment_id"]] = {"at": ev_at, "deployment_id": ev["deployment_id"], "environment": ev["environment"], "outcome": ev["outcome"], "commits": ev["commits"], "unplanned": ev["unplanned"], "caused_by": ev["caused_by"]}
        elif t == "incident":
            if "incident_id" not in ev or "phase" not in ev or "deployments" not in ev:
                raise ValueError("Malformed incident")
            i_id = ev["incident_id"]
            if i_id not in incidents:
                incidents[i_id] = {"opened": None, "resolved": None, "deployments": ev["deployments"]}
            
            if ev["phase"] == "opened":
                if incidents[i_id]["opened"] is None:
                    incidents[i_id]["opened"] = ev_at
            elif ev["phase"] == "resolved":
                if incidents[i_id]["resolved"] is None:
                    incidents[i_id]["resolved"] = ev_at

    for sha, c in commits.items():
        if c["reverts"] is not None and c["reverts"] not in commits:
            raise ValueError("reverts names missing sha")
            
    for d_id, d in deployments.items():
        for sha in d["commits"]:
            if sha not in commits:
                raise ValueError("Deployment commits names missing sha")
        if d["caused_by"] is not None and d["caused_by"] not in incidents:
            raise ValueError("Deployment caused_by names missing incident")
            
    for i_id, i in incidents.items():
        for d_id in i["deployments"]:
            if d_id not in deployments:
                raise ValueError("Incident deployments names missing deployment")
        if i["resolved"] is not None and i["opened"] is None:
            raise ValueError("Incident resolved without opened")

    def get_change_id(sha):
        seen = set()
        curr = sha
        while curr in commits:
            if curr in seen:
                break
            seen.add(curr)
            if commits[curr]["reverts"] is not None:
                curr = commits[curr]["reverts"]
            else:
                return commits[curr]["change_id"]
        return None
        
    for sha in commits:
        commits[sha]["resolved_change_id"] = get_change_id(sha)
        
    changes = {}
    for sha, c in commits.items():
        ch_id = c["resolved_change_id"]
        if ch_id is not None:
            if ch_id not in changes:
                changes[ch_id] = {"first_commit_at": c["at"]}
            else:
                if c["at"] < changes[ch_id]["first_commit_at"]:
                    changes[ch_id]["first_commit_at"] = c["at"]

    prod_deps_in_window = []
    for d_id, d in deployments.items():
        if d["environment"] == "production" and window_from <= d["at"] < window_to:
            prod_deps_in_window.append(d)

    counts = {
        "deployments": len(prod_deps_in_window),
        "successful_deployments": sum(1 for d in prod_deps_in_window if d["outcome"] == "success"),
        "failed_deployments": sum(1 for d in prod_deps_in_window if d["outcome"] == "failure"),
        "recovered_failures": 0,
        "open_failures": 0,
        "rework_deployments": sum(1 for d in prod_deps_in_window if d["unplanned"] and d["caused_by"] is not None),
        "lead_time_pairs": 0,
        "changes": len(changes)
    }
    
    anomalies = {
        "negative_lead_time_pairs": 0,
        "deployments_without_commits": 0,
        "commits_never_on_main": 0,
        "revert_chains_collapsed": sum(1 for c in commits.values() if c["reverts"] is not None),
        "overlapping_incident_pairs": 0
    }
    
    anomalies["deployments_without_commits"] = sum(1 for d in prod_deps_in_window if len(d["commits"]) == 0)
    
    off_main_shas = set()
    for d in prod_deps_in_window:
        for sha in d["commits"]:
            if sha in commits and commits[sha]["branch"] != "main":
                off_main_shas.add(sha)
    anomalies["commits_never_on_main"] = len(off_main_shas)

    first_deployments_for_commit = {}
    for d in sorted(prod_deps_in_window, key=lambda x: x["at"]):
        if d["outcome"] == "success":
            for sha in d["commits"]:
                if sha not in first_deployments_for_commit:
                    first_deployments_for_commit[sha] = d["at"]
    
    lead_times = []
    for sha, dep_at in first_deployments_for_commit.items():
        if sha in commits:
            com_at = commits[sha]["at"]
            lt = (dep_at - com_at).total_seconds()
            counts["lead_time_pairs"] += 1
            if lt < 0:
                anomalies["negative_lead_time_pairs"] += 1
                lt = 0
            lead_times.append(lt)
    
    change_lead_time_seconds_p50 = median(lead_times)
    
    window_days = (window_to - window_from).total_seconds() / 86400.0
    deployment_frequency_per_day = round_half_up(counts["deployments"] / window_days, 6) if window_days > 0 else 0.0

    recovery_times = []
    for d in prod_deps_in_window:
        if d["outcome"] == "failure":
            covering_inc = None
            for i_id, i in incidents.items():
                if d["deployment_id"] in i["deployments"] and i["opened"] is not None:
                    if covering_inc is None:
                        covering_inc = (i_id, i)
                    else:
                        if i["opened"] < covering_inc[1]["opened"]:
                            covering_inc = (i_id, i)
                        elif i["opened"] == covering_inc[1]["opened"] and i_id < covering_inc[0]:
                            covering_inc = (i_id, i)
            
            if covering_inc is not None and covering_inc[1]["resolved"] is not None:
                rt = (covering_inc[1]["resolved"] - d["at"]).total_seconds()
                if rt < 0:
                    rt = 0
                recovery_times.append(rt)
                counts["recovered_failures"] += 1
            else:
                counts["open_failures"] += 1

    failed_deployment_recovery_time_seconds_p50 = median(recovery_times)
    
    inc_intervals = []
    for i_id, i in incidents.items():
        if i["opened"] is not None:
            end_t = i["resolved"] if i["resolved"] is not None else window_to
            inc_intervals.append((i_id, i["opened"], end_t))
    
    for i in range(len(inc_intervals)):
        for j in range(i+1, len(inc_intervals)):
            a = inc_intervals[i]
            b = inc_intervals[j]
            if a[1] < b[2] and b[1] < a[2]:
                anomalies["overlapping_incident_pairs"] += 1

    denom = counts["deployments"]
    change_fail_rate = round_half_up(counts["failed_deployments"] / denom, 6) if denom > 0 else None
    deployment_rework_rate = round_half_up(counts["rework_deployments"] / denom, 6) if denom > 0 else None

    first_succ_dep_for_change = {}
    for d in sorted(prod_deps_in_window, key=lambda x: x["at"]):
        if d["outcome"] == "success":
            for sha in d["commits"]:
                if sha in commits:
                    ch_id = commits[sha]["resolved_change_id"]
                    if ch_id is not None and ch_id not in first_succ_dep_for_change:
                        first_succ_dep_for_change[ch_id] = d["at"]
                        
    ground_truth_changes_delivered = len(first_succ_dep_for_change)
    
    true_lead_times = []
    for ch_id, dep_at in first_succ_dep_for_change.items():
        com_at = changes[ch_id]["first_commit_at"]
        lt = (dep_at - com_at).total_seconds()
        if lt < 0: lt = 0
        true_lead_times.append(lt)
        
    true_change_lead_time_seconds_p50 = median(true_lead_times)

    if denom == 0:
        deployment_frequency_per_day = 0.0

    return {
        "spec_version": "1.0.0",
        "window": {"from": window["from"], "to": window["to"]},
        "deployment_frequency_per_day": deployment_frequency_per_day,
        "change_lead_time_seconds_p50": change_lead_time_seconds_p50,
        "failed_deployment_recovery_time_seconds_p50": failed_deployment_recovery_time_seconds_p50,
        "change_fail_rate": change_fail_rate,
        "deployment_rework_rate": deployment_rework_rate,
        "counts": counts,
        "anomalies": anomalies,
        "ground_truth": {
            "changes_delivered": ground_truth_changes_delivered,
            "true_change_lead_time_seconds_p50": true_change_lead_time_seconds_p50
        }
    }
